from enum import Enum


class RunStatus(str, Enum):
    CREATED = "CREATED"
    PRODUCT_ANALYZING = "PRODUCT_ANALYZING"
    PRODUCT_ANALYZED = "PRODUCT_ANALYZED"
    SCENE_ROUTING = "SCENE_ROUTING"
    SCENE_SELECTED = "SCENE_SELECTED"
    MOTION_ROUTING = "MOTION_ROUTING"
    MOTIONS_SELECTED = "MOTIONS_SELECTED"
    STORYBOARD_BUILDING = "STORYBOARD_BUILDING"
    STORYBOARD_READY = "STORYBOARD_READY"
    KEYFRAMES_GENERATING = "KEYFRAMES_GENERATING"
    KEYFRAMES_READY = "KEYFRAMES_READY"
    IMAGE_QA = "IMAGE_QA"
    IMAGE_QA_PASSED = "IMAGE_QA_PASSED"
    VIDEOS_GENERATING = "VIDEOS_GENERATING"
    VIDEOS_READY = "VIDEOS_READY"
    VIDEO_QA = "VIDEO_QA"
    VIDEO_QA_PASSED = "VIDEO_QA_PASSED"
    COMPOSING = "COMPOSING"
    COMPLETED = "COMPLETED"
    INTERRUPTED = "INTERRUPTED"
    PARTIAL_FAILED = "PARTIAL_FAILED"
    FAILED = "FAILED"


TERMINAL_STATUSES = {RunStatus.COMPLETED.value, RunStatus.FAILED.value}

